import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import '../constants/app_strings.dart';
import '../models/chat_message.dart';
import '../models/quiz.dart';

// Paste your Gemini API key here
const String apiKey = "";

class GeminiService {
  // Check if API key has been replaced by the user
  bool get isApiKeyConfigured => apiKey.isNotEmpty;

  // Helper to build a GenerativeModel with a specific system instruction
  GenerativeModel _getModel(String systemPrompt) {
    return GenerativeModel(
      model: 'gemini-2.5-flash',
      apiKey: apiKey,
      systemInstruction: Content.system(systemPrompt),
    );
  }

  /// Generates a response for a study topic, taking chat history into account.
  Future<String> generateResponse(String message, List<ChatMessage> history) async {
    if (!isApiKeyConfigured) {
      return "Please configure your Gemini API Key in `lib/services/gemini_service.dart` first.";
    }

    try {
      final model = _getModel(AppStrings.chatSystemPrompt);

      // Convert our chat history into the Content format expected by Google Generative AI
      final contents = <Content>[];
      for (var msg in history) {
        if (msg.isUser) {
          contents.add(Content.text(msg.text));
        } else {
          // Message generated by model
          contents.add(Content.model([TextPart(msg.text)]));
        }
      }

      // Add the current user query — without this line, only past history
      // gets sent and the model never actually sees what the user just asked.
      contents.add(Content.text(message));

      final response = await model.generateContent(contents);
      return response.text ?? "Sorry, I couldn't generate a response. Please try again.";
    } catch (e) {
      return "Error generating response: $e\n\nPlease verify your API key and internet connection.";
    }
  }

  /// Generates a 10-question MCQ quiz on a given topic, parses the JSON response,
  /// and returns a list of QuizQuestions.
  Future<List<QuizQuestion>> generateQuiz(String topic) async {
    if (!isApiKeyConfigured) {
      throw Exception("API Key not configured. Please paste your Gemini API Key in `lib/services/gemini_service.dart`.");
    }

    try {
      final model = _getModel(AppStrings.quizSystemPrompt);
      final prompt = "Generate a quiz on the topic: $topic";

      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text;

      if (responseText == null || responseText.isEmpty) {
        throw Exception("Received an empty response from Gemini. Please try again.");
      }

      final cleanedText = _cleanJsonResponse(responseText);
      final List<dynamic> decoded = jsonDecode(cleanedText);
      return decoded.map((q) => QuizQuestion.fromJson(q as Map<String, dynamic>)).toList();
    } catch (e) {
      debugPrint("Quiz generation error: $e");
      throw Exception("Failed to generate quiz. Please check your connection and try again.");
    }
  }

  // Strip code block markers like ```json ... ``` from response if they exist
  String _cleanJsonResponse(String response) {
    var cleaned = response.trim();
    if (cleaned.startsWith("```json")) {
      cleaned = cleaned.substring(7);
    } else if (cleaned.startsWith("```")) {
      cleaned = cleaned.substring(3);
    }
    if (cleaned.endsWith("```")) {
      cleaned = cleaned.substring(0, cleaned.length - 3);
    }
    return cleaned.trim();
  }
}